# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
      id: go
    
    - name: Ensure all files were formatted as per gofmt
      run: |
        [ "$(gofmt -l $(find . -name '*.go') 2>&1)" = "" ]
    
    - name: Run go vet
      run : go vet .

    - name: Test
      run: |
        go test ./...
        sudo nft -f .devcontainer/nftsetup.nft
        go test -c github.com/MelsRoughSketch/nftsync
        sudo ./nftsync.test -test.v -system_test
        go test -c github.com/MelsRoughSketch/nftsync/integration
        sudo ./integration.test -test.v -system_test